version: '3.7'

services:
  
  consul-server-dc1-1:
    image: hashicorp/consul:1.10
    container_name: consul-server-dc1-1
    restart: always
    volumes:
     - ./server-dc1-1.json:/consul/config/server1.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server-dc1-2:
    image: hashicorp/consul:1.10
    container_name: consul-server-dc1-2
    restart: always
    volumes:
     - ./server-dc1-2.json:/consul/config/server2.json:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-server-dc1-3:
    image: hashicorp/consul:1.10
    container_name: consul-server-dc1-3
    restart: always
    volumes:
     - ./server-dc1-3.json:/consul/config/server3.json:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client:
    image: hashicorp/consul:1.10
    container_name: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"

networks:
  consul:
    driver: bridge

